// Shipwreck ship names — vessel-style names (see tasks/shipwreck-ship-name-generator.ts for design notes).

type Pattern = (pools: Pools) => string

interface Pools {
  core: string[]
  tone: string[]
  objects: string[]
  sea: string[]
  names: string[]
  vessels: string[]
  weird: string[]
  curated: string[]
  masts: string[]
  flourish: string[]
  saltPrefix: string[]
  saltSuffix: string[]
  tail: string[]
  namesB: string[]
  hullNames: string[]
}

const pick = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)]

function pickWeightedPattern(items: { weight: number; pattern: Pattern }[]): Pattern {
  const total = items.reduce((s, i) => s + i.weight, 0)
  let r = Math.random() * total
  for (const item of items) {
    r -= item.weight
    if (r <= 0) return item.pattern
  }
  return items[items.length - 1].pattern
}

const pools: Pools = {
  core: [
    'Dream',
    'Hope',
    'Promise',
    'Mercy',
    'Fortune',
    'Grace',
    'Dawn',
    'Memory',
    'Echo',
    'Silence',
    'Truth',
    'Shadow',
    'Light',
    'Ember',
    'Bloom',
    'Rest',
    'Glory',
    'Temperance',
    'Solace',
    'Wonder',
    'Fable',
    'Peace',
    'Patience',
    'Resolve',
    'Harvest',
    'Whisper',
    'Lament',
    'Radiance',
    'Velvet',
    'Wander',
    'Voyage',
    'Vigil',
    'Vow',
    'Verse',
    'Vestige',
    'Yearning',
    'Yield',
    'Zenith',
    'Quarry',
    'Quandary',
    'Quest',
    'Union',
    'Threshold',
    'Tremor',
    'Tribute',
    'Circuit',
    'Covenant',
    'Cradle',
    'Cinder',
    'Cipher',
  ],

  tone: [
    'Last',
    'Quiet',
    'Pale',
    'Hollow',
    'Broken',
    'Distant',
    'Final',
    'Golden',
    'Fading',
    'Empty',
    'Gentle',
    'Shattered',
    'Far',
    'Low',
    'Secret',
    'Still',
    'Silver',
    'Forgotten',
    'Lonesome',
    'Soft',
    'Bitter',
    'Blind',
    'Brief',
    'Brittle',
    'Calm',
    'Cruel',
    'Curious',
    'Dim',
    'Drunken',
    'Dusky',
    'Eager',
    'Eastern',
    'Errant',
    'Faint',
    'False',
    'Feral',
    'Fickle',
    'Fleet',
    'Frail',
    'Frozen',
    'Gilded',
    'Grim',
    'Half',
    'Hidden',
    'Icy',
    'Jagged',
    'Jolly',
    'Kindly',
    'Lean',
    'Lucky',
    'Lunar',
    'Merry',
    'Misty',
    'Moody',
    'Mute',
    'Narrow',
    'Northern',
    'Odd',
    'Open',
    'Patient',
    'Primal',
    'Proud',
    'Ragged',
    'Rapid',
    'Raw',
    'Restless',
    'Royal',
    'Rusty',
    'Sable',
    'Savage',
    'Second',
    'Shy',
    'Sleepy',
    'Slender',
    'Smiling',
    'Sober',
    'Solar',
    'Solemn',
    'Sour',
    'Southern',
    'Stark',
    'Steady',
    'Steel',
    'Sterling',
    'Stormy',
    'Strange',
    'Strict',
    'Sudden',
    'Sullen',
    'Sunny',
    'Sure',
    'Swift',
    'Tangled',
    'Tender',
    'Thirsty',
    'Timid',
    'Tiny',
    'Tired',
    'Truant',
    'Trusty',
    'Twin',
    'Uncanny',
    'Vague',
    'Vivid',
    'Wary',
    'Waxen',
    'Weary',
    'Western',
    'Wet',
    'Wicked',
    'Wild',
    'Wily',
    'Winged',
    'Wintry',
    'Wise',
    'Wistful',
    'Worthy',
    'Young',
    'Zealous',
  ],

  objects: [
    'Star',
    'Crown',
    'Lantern',
    'Path',
    'Song',
    'Oath',
    'Beacon',
    'Flame',
    'Thread',
    'Sky',
    'Vale',
    'Horizon',
    'Rose',
    'Bell',
    'Feather',
    'Branch',
    'Torch',
    'Mirror',
    'Banner',
    'Bridge',
    'Arrow',
    'Compass',
    'Anchor',
    'Coral',
    'Cradle',
    'Crest',
    'Dagger',
    'Dial',
    'Drum',
    'Eagle',
    'Falcon',
    'Finch',
    'Flute',
    'Folly',
    'Forge',
    'Fountain',
    'Garden',
    'Garnet',
    'Gate',
    'Gem',
    'Ghost',
    'Goblet',
    'Gull',
    'Hammer',
    'Harp',
    'Hawk',
    'Heart',
    'Helm',
    'Heron',
    'Horn',
    'Hound',
    'Hummingbird',
    'Hyacinth',
    'Ibis',
    'Idol',
    'Ingot',
    'Iris',
    'Island',
    'Ivory',
    'Jade',
    'Jewel',
    'Juniper',
    'Kite',
    'Knife',
    'Knot',
    'Lagoon',
    'Lark',
    'Laurel',
    'Ledger',
    'Legend',
    'Liberty',
    'Lily',
    'Lion',
    'Locket',
    'Lotus',
    'Maiden',
    'Mallet',
    'Mantle',
    'Marble',
    'Marrow',
    'Mask',
    'Mermaid',
    'Minnow',
    'Mockingbird',
    'Monarch',
    'Moon',
    'Moor',
    'Morning',
    'Moss',
    'Moth',
    'Nautilus',
    'Nectar',
    'Netsuke',
    'Nightjar',
    'Oak',
    'Obsidian',
    'Onyx',
    'Opal',
    'Orchid',
    'Osprey',
    'Owl',
    'Pearl',
    'Pelican',
    'Pendant',
    'Perch',
    'Petal',
    'Pillar',
    'Pilot',
    'Pinnacle',
    'Plover',
    'Plum',
    'Pomegranate',
    'Poppy',
    'Prow',
    'Pyre',
    'Quartz',
    'Quill',
    'Quiver',
    'Raven',
    'Reed',
    'Relic',
    'Ribbon',
    'Riddle',
    'Ridge',
    'Rifle',
    'Ring',
    'Rivet',
    'Rocket',
    'Root',
    'Rope',
    'Rosary',
    'Rudder',
    'Rune',
    'Sable',
    'Sail',
    'Sapphire',
    'Scepter',
    'Scroll',
    'Scythe',
    'Serpent',
    'Shackles',
    'Shepherd',
    'Shield',
    'Shrine',
    'Shroud',
    'Shrub',
    'Sickle',
    'Sigil',
    'Silver',
    'Siren',
    'Slate',
    'Sledge',
    'Sloop',
    'Snare',
    'Snipe',
    'Socket',
    'Spar',
    'Spear',
    'Sphere',
    'Spindle',
    'Spire',
    'Spoon',
    'Spur',
    'Squall',
    'Staff',
    'Stag',
    'Stallion',
    'Statue',
    'Steeple',
    'Stencil',
    'Stiletto',
    'Stone',
    'Stork',
    'Strand',
    'Strap',
    'Stream',
    'Strike',
    'String',
    'Stylus',
    'Summit',
    'Sun',
    'Surcoat',
    'Swan',
    'Sword',
    'Table',
    'Talon',
    'Tambour',
    'Tangle',
    'Tapestry',
    'Tassel',
    'Temple',
    'Tern',
    'Thistle',
    'Thorn',
    'Throne',
    'Tile',
    'Timber',
    'Tinder',
    'Tome',
    'Totem',
    'Tower',
    'Trammel',
    'Trident',
    'Trim',
    'Trinket',
    'Triumph',
    'Troll',
    'Trumpet',
    'Trundle',
    'Tuber',
    'Tulip',
    'Tundra',
    'Tunnel',
    'Turret',
    'Turtle',
    'Twine',
    'Tyrant',
  ],

  sea: [
    'Tide',
    'Wake',
    'Current',
    'Reach',
    'Deep',
    'Drift',
    'Sound',
    'Harbor',
    'Shoal',
    'Channel',
    'Surf',
    'Swell',
    'Breaker',
    'Bar',
    'Basin',
    'Bay',
    'Beach',
    'Billow',
    'Brine',
    'Brook',
    'Cape',
    'Chart',
    'Chop',
    'Cliff',
    'Cove',
    'Creek',
    'Crest',
    'Dock',
    'Dory',
    'Down',
    'Dune',
    'Eddy',
    'Eel',
    'Estuary',
    'Fetch',
    'Fjord',
    'Flats',
    'Fleet',
    'Flood',
    'Foam',
    'Fog',
    'Ford',
    'Gale',
    'Gulf',
    'Gully',
    'Haul',
    'Haven',
    'Head',
    'Heave',
    'Helm',
    'Hook',
    'Hull',
    'Inlet',
    'Island',
    'Jetty',
    'Keel',
    'Kelp',
    'Knot',
    'Lagoon',
    'League',
    'Lee',
    'Line',
    'List',
    'Marl',
    'Mooring',
    'Narrows',
    'Neap',
    'Ocean',
    'Offing',
    'Pass',
    'Peel',
    'Pier',
    'Pilot',
    'Pinnacle',
    'Pitch',
    'Plank',
    'Plate',
    'Point',
    'Pond',
    'Pool',
    'Port',
    'Prow',
    'Puff',
    'Quay',
    'Race',
    'Ramp',
    'Range',
    'Reef',
    'Ridge',
    'Rip',
    'Road',
    'Roll',
    'Rope',
    'Rudder',
    'Run',
    'Salt',
    'Sand',
    'Scarp',
    'Sea',
    'Seam',
    'Shingle',
    'Side',
    'Skerry',
    'Slack',
    'Sleet',
    'Slip',
    'Snag',
    'Spill',
    'Spindrift',
    'Spit',
    'Spray',
    'Stack',
    'Stage',
    'Starboard',
    'Steer',
    'Stem',
    'Step',
    'Stern',
    'Stirrup',
    'Stone',
    'Storm',
    'Strait',
    'Stream',
    'Strike',
    'Surge',
    'Swash',
    'Swing',
    'Tack',
    'Tank',
    'Thwart',
    'Tombolo',
    'Tow',
    'Tower',
    'Track',
    'Trade',
    'Trap',
    'Trim',
    'Trough',
    'Trunk',
    'Tsunami',
    'Undertow',
    'Veer',
    'Vessel',
    'Wall',
    'Warp',
    'Wash',
    'Water',
    'Wave',
    'Way',
    'Weed',
    'Well',
    'Whelm',
    'Whirlpool',
    'Wind',
    'Wing',
    'Wreck',
    'Yard',
    'Yaw',
    'Zephyr',
  ],

  names: [
    'Avel',
    'Corin',
    'Selka',
    'Brann',
    'Ilyra',
    'Venn',
    'Orin',
    'Cael',
    'Mirek',
    'Sora',
    'Talven',
    'Neris',
    'Aro',
    'Velis',
    'Junor',
    'Mera',
    'Cairn',
    'Letha',
    'Drusa',
    'Eldin',
    'Fenra',
    'Gorven',
    'Hollis',
    'Isolt',
    'Jareth',
    'Kessa',
    'Liora',
    'Morcant',
    'Nysa',
    'Orien',
    'Perrin',
    'Quilla',
    'Riven',
    'Sable',
    'Tamsin',
    'Ulwen',
    'Varis',
    'Wysta',
    'Ysolde',
    'Arden',
    'Bex',
    'Coralie',
    'Dain',
    'Estra',
    'Fiske',
    'Garr',
    'Hale',
    'Indra',
    'Jory',
    'Kael',
    'Lorne',
    'Maren',
    'Nix',
    'Ode',
    'Pike',
    'Quin',
    'Rook',
    'Soren',
    'Tove',
    'Urien',
    'Vex',
    'Wren',
    'Yarrow',
    'Zinn',
  ],

  namesB: [
    'Maris',
    'Torin',
    'Elka',
    'Duroc',
    'Fenn',
    'Glynn',
    'Hask',
    'Ivara',
    'Jex',
    'Korr',
    'Lys',
    'Myrr',
    'Nox',
    'Otta',
    'Prynn',
    'Rafe',
    'Sylt',
    'Tarn',
    'Ulf',
    'Vire',
    'Wyst',
    'Yul',
    'Zeth',
    'Afton',
    'Briar',
    'Clove',
    'Edda',
    'Flint',
    'Gorse',
    'Inis',
    'Jute',
    'Kest',
    'Molt',
    'Nye',
    'Orlo',
    'Quor',
    'Rill',
    'Stip',
    'Umber',
    'Voss',
    'Wex',
    'Yew',
    'Zora',
  ],

  vessels: [
    'Promise',
    'Folly',
    'Oath',
    'Venture',
    'Return',
    'Crossing',
    'Light',
    'Dream',
    'Mercy',
    'Beacon',
    'Fortune',
    'Silence',
    'Star',
    'Horizon',
    'Reckoning',
    'Ransom',
    'Quarrel',
    'Grudge',
    'Leisure',
    'Wager',
    'Tally',
    'Score',
    'Vow',
    'Pledge',
    'Bond',
    'Charter',
    'Writ',
    'Decree',
    'Verdict',
    'Judgment',
    'Answer',
    'Claim',
    'Share',
    'Lot',
    'Part',
    'Balance',
    'Boon',
    'Bane',
    'Curse',
    'Blessing',
    'Quandary',
    'Dilemma',
    'Truce',
    'Treaty',
    'Accord',
    'Pact',
    'Compact',
    'League',
    'Union',
    'Lien',
    'Debt',
    'Note',
    'Cause',
    'Case',
    'Suit',
    'Bill',
    'Fine',
    'Remedy',
    'Reprieve',
    'Reprisal',
    'Restitution',
    'Revelry',
    'Riddle',
    'Rigor',
    'Rivalry',
    'Romance',
    'Roster',
    'Ruckus',
    'Ruin',
    'Rule',
    'Rumor',
    'Rush',
    'Salvo',
    'Sanction',
    'Scandal',
    'Scruple',
    'Season',
    'Secret',
    'Sentence',
    'Shadow',
    'Shame',
    'Shape',
    'Shelter',
    'Shift',
    'Shrine',
    'Signal',
    'Skein',
    'Solace',
    'Sorrow',
    'Soul',
    'Spark',
    'Speech',
    'Spell',
    'Spirit',
    'Splendor',
    'Spoil',
    'Sport',
    'Spray',
    'Spring',
    'Sprite',
    'Spur',
    'Squall',
    'Stanza',
    'Stark',
    'Steed',
    'Steer',
    'Steward',
    'Stipend',
    'Stoic',
    'Stone',
    'Storm',
    'Strait',
    'Strand',
    'Strange',
    'Stream',
    'Stride',
    'Strife',
    'Strike',
    'String',
    'Strive',
    'Stroke',
    'Strong',
    'Summit',
    'Sunder',
    'Sunset',
    'Supper',
    'Surface',
    'Surge',
    'Survey',
    'Survivor',
    'Swallow',
    'Swan',
    'Sway',
    'Sweep',
    'Sweet',
    'Swell',
    'Swift',
    'Swing',
    'Swirl',
    'Sword',
    'Sworn',
    'Symbol',
    'Epitaph',
    'Relic',
    'Tribute',
    'Offering',
    'Oblation',
    'Memorial',
    'Ledger',
    'Covenant',
    'Commission',
    'Mandate',
    'Summons',
    'Inquest',
    'Inquiry',
    'Redress',
    'Reparation',
    'Amends',
    'Atonement',
    'Absolution',
    'Indulgence',
    'Dispensation',
    'Privilege',
    'Prerogative',
    'Mandamus',
    'Injunction',
    'Subpoena',
    'Affidavit',
    'Testimony',
    'Evidence',
    'Exhibit',
    'Appendix',
    'Addendum',
    'Codex',
    'Canon',
    'Credo',
    'Doctrine',
    'Dogma',
    'Tenet',
    'Axiom',
    'Theorem',
    'Lemma',
    'Corollary',
    'Premise',
    'Thesis',
    'Antithesis',
    'Synthesis',
    'Hypothesis',
    'Postulate',
    'Conjecture',
    'Surmise',
    'Notion',
    'Concept',
    'Idea',
    'Image',
    'Idyll',
    'Eclogue',
    'Pastoral',
    'Ballad',
    'Lay',
    'Carol',
    'Roundel',
    'Rondeau',
    'Sestina',
    'Villanelle',
    'Sonnet',
    'Ode',
    'Elegy',
    'Dirge',
    'Requiem',
    'Canticle',
    'Hymn',
    'Anthem',
    'Psalm',
    'Chant',
    'Litany',
    'Rosary',
    'Vigil',
    'Watch',
    'Ward',
    'Warrant',
    'Patent',
    'Deed',
    'Title',
    'Stake',
    'Portion',
    'Measure',
    'Account',
  ],

  weird: [
    'Without End',
    'That Remains',
    'Before Dawn',
    'That Waits',
    'Without Return',
    'Beyond the Sound',
    'After Silence',
    'Before the Deep',
    'In the Shallows',
    'Of No Harbor',
    'Lost to Fog',
    'With No Name',
    'Against the Gale',
    'Under False Colors',
    'In Good Faith',
    'By Star Alone',
    'On Borrowed Wind',
    'At the Bar',
    'Where the Map Ends',
    'When the Tide Turns',
    'If the Wind Holds',
    'Though the Stars Fail',
    'When the Bell Tolls',
    'Where the Reef Sleeps',
    'Beyond the Chart',
    'Past the Headland',
    'Near the Races',
    'Off the Soundings',
    'Inside the Lee',
    'Outside the Law',
  ],

  tail: [
    'of the Outer Isles',
    'of the North Road',
    'of the Long Sand',
    'of the Short Sea',
    'of the Grey Strait',
    'of the White Cliffs',
    'of the Black Bar',
    'of the Third Moon',
    'of the First Frost',
    'of the Last Port',
    'of the Salt House',
    'of the Copper Dock',
    'of the Iron Pier',
    'of the Silver Fleet',
    'of the Gold Coast',
    'of the Amber Bay',
    'of the Green Run',
    'of the Red Reach',
    'of the Blue Hook',
    'of the Violet Shoal',
    'from the Ice',
    'from the Sun',
    'from the Mist',
    'from the Storm',
    'from the West',
    'from the East',
    'from the South',
    'from the Farther Shore',
    'from Nowhere',
    'from Everywhere',
  ],

  masts: [
    'Chaser',
    'Packet',
    'Runner',
    'Revenant',
    'Tern',
    'Petrel',
    'Albatross',
    'Dart',
    'Skylark',
    'Widow',
    'Reef',
    'Rascal',
    'Ransom',
    'Raven',
    'Garland',
    'Gannet',
    'Plover',
    'Puffin',
    'Shearwater',
    'Cormorant',
    'Pelican',
    'Cutlass',
    'Cutter',
    'Clipper',
    'Schooner',
    'Brig',
    'Barque',
    'Lugger',
    'Smack',
    'Hoy',
    'Pink',
    'Pinnace',
    'Longboat',
    'Whaler',
    'Trawler',
    'Drifter',
    'Smuggler',
    'Buccaneer',
    'Corsair',
    'Raider',
    'Rover',
    'Voyager',
    'Wanderer',
    'Straggler',
    'Stowaway',
    'Castaway',
    'Outrider',
    'Pathfinder',
    'Wayfinder',
    'Starling',
    'Swallow',
    'Swift',
    'Arrow',
    'Bolt',
    'Flare',
    'Spark',
    'Ember',
    'Cinder',
    'Ash',
    'Soot',
    'Brine',
    'Spray',
    'Spume',
    'Spindrift',
    'Breaker',
    'Comber',
    'Roller',
    'Swell',
    'Surge',
    'Eddy',
    'Pool',
    'Well',
    'Basin',
    'Bight',
    'Gully',
    'Gulch',
    'Notch',
    'Gap',
    'Pass',
    'Step',
    'Stile',
    'Gate',
    'Post',
    'Mark',
    'Mile',
    'League',
    'Bell',
    'Knell',
    'Peal',
    'Chime',
    'Hymn',
    'Dirge',
    'Lay',
    'Ballad',
    'Carol',
    'Round',
    'Refrain',
    'Verse',
    'Canto',
    'Stanza',
    'Line',
    'Couplet',
    'Rhyme',
    'Meter',
    'Foot',
    'Beat',
    'Pulse',
    'Throb',
    'Drum',
    'Kestrel',
    'Merlin',
    'Osprey',
    'Harrier',
    'Shrike',
    'Nighthawk',
    'Bittern',
    'Curlew',
    'Avocet',
    'Sandpiper',
    'Godwit',
    'Turnstone',
    'Redshank',
    'Greenshank',
    'Woodcock',
    'Snipe',
    'Rail',
    'Coot',
    'Grebe',
    'Diver',
    'Auk',
    'Guillemot',
    'Murre',
    'Razorbill',
    'Skua',
    'Jaeger',
    'Frigate',
    'Man-o-war',
    'Junk',
    'Dhow',
    'Felucca',
    'Caravel',
    'Carrack',
    'Galleon',
    'Fluyt',
    'Buss',
    'Ketch',
    'Yawl',
    'Dinghy',
    'Coble',
    'Punt',
    'Wherry',
    'Skiff',
    'Dory',
    'Catboat',
    'Sloop',
    'Bark',
    'Snow',
    'Xebec',
    'Polacre',
    'Tartane',
    'Dogger',
    'Hoeker',
    'Galiot',
  ],

  flourish: [
    'Old',
    'Fair',
    'Bold',
    'Sharp',
    'Swift',
    'True',
    'Young',
    'Free',
    'Deep',
    'High',
    'Cold',
    'Wild',
    'Sweet',
    'Long',
    'Poor',
    'Rich',
    'Bare',
    'Black',
    'Blue',
    'Bright',
    'Broad',
    'Brown',
    'Clean',
    'Clear',
    'Close',
    'Coarse',
    'Cool',
    'Cruel',
    'Dark',
    'Dead',
    'Dear',
    'Dense',
    'Dry',
    'Dull',
    'Early',
    'Easy',
    'Edgy',
    'Elfin',
    'Evil',
    'False',
    'Fast',
    'Fat',
    'Fierce',
    'Fine',
    'Firm',
    'Flat',
    'Fleet',
    'Fond',
    'Foul',
    'Frank',
    'Fresh',
    'Full',
    'Gay',
    'Glad',
    'Good',
    'Grand',
    'Great',
    'Grey',
    'Grim',
    'Gross',
    'Half',
    'Hard',
    'Harsh',
    'Heady',
    'Heavy',
    'Hind',
    'Hoar',
    'Holy',
    'Hot',
    'Huge',
    'Idle',
    'Ill',
    'Just',
    'Keen',
    'Kind',
    'Lank',
    'Large',
    'Late',
    'Lean',
    'Left',
    'Lewd',
    'Light',
    'Like',
    'Live',
    'Lone',
    'Loud',
    'Low',
    'Loyal',
    'Mad',
    'Main',
    'Male',
    'Mean',
    'Meek',
    'Mere',
    'Mild',
    'Mind',
    'Mint',
    'Near',
    'Neat',
    'New',
    'Nice',
    'Nigh',
    'Noble',
    'Odd',
    'Oft',
    'Open',
    'Oval',
    'Pale',
    'Past',
    'Peak',
    'Petty',
    'Plain',
    'Plump',
    'Polar',
    'Posh',
    'Prime',
    'Prim',
    'Proud',
    'Pure',
    'Quick',
    'Rare',
    'Raw',
    'Real',
    'Red',
    'Rife',
    'Right',
    'Rigid',
    'Ripe',
    'Rude',
    'Rum',
    'Sad',
    'Safe',
    'Sage',
    'Same',
    'Sane',
    'Scant',
    'Scar',
    'Scud',
    'Sea',
    'Seam',
    'Sheer',
    'Short',
    'Shy',
    'Sick',
    'Side',
    'Sift',
    'Sign',
    'Silk',
    'Silly',
    'Simple',
    'Single',
    'Sixth',
    'Slack',
    'Sleek',
    'Slight',
    'Slim',
    'Slow',
    'Small',
    'Smart',
    'Smooth',
    'Snug',
    'Soft',
    'Sold',
    'Solid',
    'Some',
    'Sore',
    'Sour',
    'Spare',
    'Stark',
    'Steep',
    'Stiff',
    'Still',
    'Stock',
    'Stone',
    'Storm',
    'Straight',
    'Strange',
    'Strict',
    'Strong',
    'Such',
    'Sudden',
    'Sullen',
    'Sunny',
    'Sure',
    'Tall',
    'Tame',
    'Tart',
    'Taut',
    'Tense',
    'Thick',
    'Thin',
    'Third',
    'Tidy',
    'Tight',
    'Tiny',
    'Tired',
    'Toft',
    'Told',
    'Torn',
    'Tough',
    'Trim',
    'Twin',
    'Ugly',
    'Vain',
    'Vast',
    'Vile',
    'Void',
    'Vulgar',
    'Wan',
    'Warm',
    'Warp',
    'Weak',
    'Weal',
    'Weft',
    'Well',
    'West',
    'Wet',
    'Wide',
    'Wily',
    'Wing',
    'Wise',
    'Wist',
    'Woe',
    'Wood',
    'Worn',
    'Wry',
    'Yare',
    'Yellow',
    'Zany',
  ],

  saltPrefix: [
    'Salt',
    'Sea',
    'Storm',
    'Foam',
    'Kelp',
    'Ice',
    'Iron',
    'Copper',
    'Amber',
    'Brine',
    'Tide',
    'Wave',
    'Wind',
    'Mist',
    'Fog',
    'Gale',
    'Reef',
    'Sand',
    'Shell',
    'Pearl',
    'Coral',
    'Drift',
    'Spray',
    'Spume',
    'Swell',
    'Surge',
    'Ebb',
    'Flood',
    'Dusk',
    'Dawn',
    'Noon',
    'Night',
    'Moon',
    'Star',
    'Sun',
    'Cloud',
    'Rain',
    'Hail',
    'Snow',
    'Frost',
    'Flame',
    'Ash',
    'Ember',
    'Coal',
    'Steel',
    'Silver',
    'Gold',
    'Lead',
    'Tin',
    'Rust',
    'Blood',
    'Wine',
    'Milk',
    'Honey',
    'Vine',
    'Thorn',
    'Rose',
    'Lily',
    'Oak',
    'Elm',
    'Ashwood',
    'Pine',
    'Birch',
    'Yew',
    'Haw',
    'Holly',
    'Ivy',
    'Fern',
    'Moss',
    'Lichen',
    'Bone',
    'Skull',
    'Ghost',
    'Wraith',
    'Shade',
    'Gloom',
    'Gleam',
    'Glint',
    'Spark',
    'Flash',
    'Bolt',
    'Crash',
    'Crack',
    'Snap',
    'Pop',
    'Hiss',
    'Buzz',
    'Hum',
    'Song',
    'Tune',
    'Chord',
    'Note',
    'Rest',
    'Beat',
    'Pulse',
    'Tick',
    'Tock',
    'Bell',
    'Knell',
    'Peal',
    'Chime',
    'Hymn',
    'Dirge',
    'Lay',
    'Ballad',
    'Carol',
    'Round',
    'Refrain',
    'Verse',
    'Canto',
    'Stanza',
    'Line',
    'Couplet',
    'Rhyme',
    'Meter',
    'Foot',
  ],

  saltSuffix: [
    'wake',
    'line',
    'born',
    'tooth',
    'gate',
    'mark',
    'fall',
    'crest',
    'runner',
    'chaser',
    'seeker',
    'finder',
    'keeper',
    'weaver',
    'winder',
    'binder',
    'sender',
    'mender',
    'bender',
    'fender',
    'lender',
    'cinder',
    'hinder',
    'wander',
    'yonder',
    'fonder',
    'ponder',
    'blunder',
    'plunder',
    'thunder',
    'asunder',
    'slumber',
    'amber',
    'ember',
    'glimmer',
    'shimmer',
    'flicker',
    'cracker',
    'packer',
    'looker',
    'broker',
    'worker',
    'lurker',
    'mercer',
    'dancer',
    'prancer',
    'mincer',
    'rinser',
  ],

  hullNames: [
    'Chaser',
    'Packet',
    'Runner',
    'Revenant',
    'Tern',
    'Petrel',
    'Dart',
    'Skylark',
    'Widow',
    'Rascal',
    'Ransom',
    'Cutlass',
    'Cutter',
    'Clipper',
    'Schooner',
    'Brig',
    'Barque',
    'Lugger',
    'Smack',
    'Hoy',
    'Pinnace',
    'Whaler',
    'Trawler',
    'Drifter',
    'Smuggler',
    'Corsair',
    'Raider',
    'Rover',
    'Voyager',
    'Wanderer',
    'Straggler',
    'Outrider',
    'Wayfinder',
    'Starling',
    'Swallow',
    'Arrow',
    'Bolt',
    'Flare',
    'Spark',
    'Comber',
    'Roller',
    'Eddy',
    'Bight',
    'Notch',
    'Stile',
    'Knell',
    'Lay',
    'Round',
    'Meter',
    'Throb',
    'Rattle',
    'Clack',
    'Crack',
    'Hush',
    'Murmur',
    'Sough',
    'Kestrel',
    'Osprey',
    'Felucca',
    'Caravel',
    'Galleon',
    'Xebec',
    'Dogger',
    'Hoeker',
    'Wherry',
    'Skiff',
    'Coble',
  ],

  curated: [
    'The Dream',
    'The Quiet Star',
    'The Last Light',
    'The Hollow Crown',
    'The Golden Path',
    'The Gentle Flame',
    'The Silent Horizon',
    'The Shattered Song',
    "Avel's Promise",
    "Selka's Venture",
    'The Light Without End',
    'The Tide Before Dawn',
    'Good Fortune',
    'Fair Wind',
    "Lady's Lament",
    "Bachelor's Delight",
    'Sea-Nymph',
    'Foam-Breast',
    "John's Desire",
    'Our Lady of Sorrows',
    'Prince of Aquitaine',
    'Dutch Galliot',
    'French Leave',
    'Spanish Main',
    'Portuguese Man o War',
    'Bristol Packet',
    'London Trader',
    'Hull Snow',
    'Yarmouth Fisher',
    'Scilly Rover',
    'Hebridean Reel',
    'Orkney Yawl',
    'Shetland Bus',
    'Dogger Bank',
    'Nore Lightship',
    'Eddystone',
    'Bell Rock',
    'Fastnet',
    'Lizard Point',
    "Land's End",
    'Cape Wrath',
    'Finisterre',
    'Bay of Biscay',
    'Strait Answer',
    'Narrow Escape',
    'Wide Berth',
    'Keelhaul Justice',
    'Jury Mast',
    'Coffin Ship',
    'Ghost Fleet',
    'Paper Captain',
    'Salt Wife',
    'Rum Contract',
    'Powder Monkey',
    'Crown Colony',
    'East Indiaman',
    'Westward Ho',
    'Homeward Bound',
    'No Return',
    'Last Trip',
    'First Landfall',
    'Second Sight',
    'Third Reef',
    'Fourth Watch',
    'Fifth Column',
    'Sixth Sense',
    'Seventh Wave',
    'Eighth Bell',
    'Ninth Circle',
    'Tenth Muse',
  ],
}

const weightedPatterns: { weight: number; pattern: Pattern }[] = [
  { weight: 1, pattern: (p) => `The ${pick(p.core)}` },
  { weight: 1, pattern: (p) => `The ${pick(p.tone)} ${pick(p.objects)}` },
  { weight: 1, pattern: (p) => `The ${pick(p.tone)} ${pick(p.core)}` },
  { weight: 4, pattern: (p) => `${pick(p.names)}'s ${pick(p.vessels)}` },
  { weight: 1, pattern: (p) => `The ${pick(p.tone)} ${pick(p.sea)}` },
  { weight: 1, pattern: (p) => `The ${pick(p.core)} ${pick(p.weird)}` },
  { weight: 5, pattern: (p) => `${pick(p.flourish)} ${pick(p.masts)}` },
  { weight: 4, pattern: (p) => `${pick(p.sea)} ${pick(p.objects)}` },
  { weight: 3, pattern: (p) => `Good ${pick(p.core)}` },
  { weight: 3, pattern: (p) => `Fair ${pick(p.objects)}` },
  { weight: 3, pattern: (p) => `Old ${pick(p.masts)}` },
  { weight: 3, pattern: (p) => `Little ${pick(p.objects)}` },
  { weight: 4, pattern: (p) => `${pick(p.names)}'s ${pick(p.hullNames)}` },
  { weight: 3, pattern: (p) => `${pick(p.namesB)}'s ${pick(p.hullNames)}` },
  { weight: 3, pattern: (p) => `Lady ${pick(p.core)}` },
  { weight: 2, pattern: (p) => `Saint ${pick(p.objects)}` },
  { weight: 4, pattern: (p) => `${pick(p.core)} ${pick(p.tail)}` },
  { weight: 4, pattern: (p) => `${capitalize(pick(p.saltPrefix))}${pick(p.saltSuffix)}` },
  { weight: 2, pattern: (p) => `${pick(p.sea)}-${pick(p.objects)}` },
  { weight: 4, pattern: (p) => `${pick(p.flourish)} ${pick(p.names)}` },
  { weight: 2, pattern: (p) => `True ${pick(p.core)}` },
  { weight: 2, pattern: (p) => `Bold ${pick(p.sea)}` },
  { weight: 2, pattern: (p) => `Cold ${pick(p.objects)}` },
  { weight: 4, pattern: (p) => `${pick(p.names)} ${pick(p.namesB)}` },
  { weight: 2, pattern: (p) => `The ${pick(p.objects)} ${pick(p.tail)}` },
  { weight: 3, pattern: (p) => `My ${pick(p.core)}` },
  { weight: 3, pattern: (p) => `Our ${pick(p.objects)}` },
  { weight: 2, pattern: (p) => `${pick(p.names)} & ${pick(p.namesB)}` },
  { weight: 2, pattern: (p) => `Never ${pick(p.vessels)}` },
  { weight: 2, pattern: (p) => `Half ${pick(p.masts)}` },
]

function capitalize(s: string): string {
  if (!s) return s
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function isBadName(name: string): boolean {
  const lower = name.toLowerCase()

  const words = lower
    .replace(/[^a-z\s']/g, '')
    .split(/\s+/)
    .filter(Boolean)
  const uniqueWords = new Set(words)
  if (uniqueWords.size !== words.length) return true

  const bannedExact = new Set([
    'the broken broken',
    'the hollow hollow',
    'the empty emptiness',
    'fair fair',
    'old old',
    'good good',
    'true true',
    'bold bold',
    'cold cold',
  ])
  if (bannedExact.has(lower)) return true

  if (words.length === 2 && words[0] === words[1]) return true

  return false
}

export function generateShipwreckShipName(): string {
  if (Math.random() < 0.12) {
    return pick(pools.curated)
  }

  let attempts = 0

  while (attempts < 48) {
    const pattern = pickWeightedPattern(weightedPatterns)
    const candidate = pattern(pools)

    if (!isBadName(candidate)) {
      return candidate
    }

    attempts += 1
  }

  return pick(pools.curated)
}

export function generateShipwreckShipNames(count: number): string[] {
  const results = new Set<string>()

  while (results.size < count) {
    results.add(generateShipwreckShipName())
  }

  return Array.from(results)
}
